### ISSUE TITLE
Can't create hotspot

### ISSUE THREAD

**Issue by Djaler** [elementary/switchboard-plug-networking#101]
Juno. When I try to create a hotspot, I get this error:
`(switchboard:4044): GLib-ERROR **: 15:40:40.317: ../../../../glib/gmem.c:170: failed to allocate 137438953472 bytes`

**Comment by danrabbit** [comment]
I have a backtrace for this:

```
(switchboard:26508): GLib-ERROR **: 14:06:20.689: ../../../../glib/gmem.c:170: failed to allocate 137438953472 bytes

Thread 1 "switchboard" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff6003c41 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff6003c41 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff6004c7c in g_log_default_handler () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6004f0d in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff600507f in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff6003939 in g_realloc () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff65e0d99 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff65e1785 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff65e15bc in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007ffff65e1638 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007ffff65e10d5 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007ffff65e1638 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007ffff65e10d5 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x00007ffff65e3d30 in g_dbus_message_to_blob () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007ffff65d82dc in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007ffff65d9746 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007ffff65dc7a2 in g_dbus_connection_send_message_with_reply () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007ffff65dcb6a in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007ffff65e90d5 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x00007ffff65ea946 in g_dbus_proxy_call () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x00007fffced2b0f7 in  () at /usr/lib/x86_64-linux-gnu/libnm.so.0
#20 0x00007fffcecac215 in nm_client_add_and_activate_connection_async () at /usr/lib/x86_64-linux-gnu/libnm.so.0
#21 0x00007fffcef854a1 in network_utils_hotspot_activate_hotspot (wifi_device=0x5555569561b0, ssid=0x7fffd80a9b80, key=0x5555561e0120 "secretsquirrel", selected=0x0) at /home/daniel/Projects/switchboard-plug-networking/src/Utils.vala:85
#22 0x00007fffcef9915b in ___lambda28_ (_data11_=0x5555559d0460, response=1)
    at /home/daniel/Projects/switchboard-plug-networking/src/Widgets/HotspotInterface.vala:106
#23 0x00007fffcef991fd in ____lambda28__gtk_dialog_response (_sender=0x555556448480, response_id=1, self=0x5555559d0460)
    at /home/daniel/Projects/switchboard-plug-networking/src/Widgets/HotspotInterface.vala:104
#24 0x00007ffff62d7f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff62ead3e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007ffff62f33f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff62d81a6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff62f36df in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007ffff69e77dd in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#32 0x00007ffff69e7835 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff62d7f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff62eae0e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff62f33f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff69e5c90 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff1902dae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#39 0x00007ffff190271f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#40 0x00007ffff62d8b4d in g_cclosure_marshal_generic_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007ffff62d81a6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007ffff62f36df in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff6aa24f6 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007ffff62dae68 in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff62d81a6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff62f36df in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#48 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x00007ffff6a9f7ce in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#50 0x00007ffff6aa0dbb in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#51 0x00007ffff6aa3a1e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007ffff6a71241 in gtk_event_controller_handle_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x00007ffff6c3066b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#54 0x00007ffff6aeb1b7 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007ffff62d81a6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#56 0x00007ffff62f30ad in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#57 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#58 0x00007ffff6c32904 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#59 0x00007ffff6ae813e in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x00007ffff6aea208 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#61 0x00007ffff56fe965 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#62 0x00007ffff572f182 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#63 0x00007ffff5ffe287 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#64 0x00007ffff5ffe4c0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#65 0x00007ffff5ffe7d2 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#66 0x00007ffff6a58953 in gtk_dialog_run () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#67 0x00007fffcef994bd in network_widgets_hotspot_interface_real_control_switch_activated (base=0x555555d5ccf0)
    at /home/daniel/Projects/switchboard-plug-networking/src/Widgets/HotspotInterface.vala:117
#68 0x00007fffcef941a4 in network_widgets_page_control_switch_activated (self=0x555555d5ccf0)
    at /home/daniel/Projects/switchboard-plug-networking/src/Widgets/Page.vala:126
#69 0x00007fffcef934a2 in _network_widgets_page_control_switch_activated_g_object_notify (_sender=0x555556956d70, pspec=0x555555f35570, self=0x555555d5ccf0) at /home/daniel/Projects/switchboard-plug-networking/src/Widgets/Page.vala:89
#70 0x00007ffff62d7f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#71 0x00007ffff62ead3e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#72 0x00007ffff62f33f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#73 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#74 0x00007ffff62dc424 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#75 0x00007ffff62de969 in g_object_notify_by_pspec () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#76 0x00007ffff6b9eade in gtk_switch_set_active () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#77 0x00007ffff6b9ef28 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#78 0x00007ffff6c33a02 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#79 0x00007ffff62d7f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#80 0x00007ffff62ead3e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#81 0x00007ffff62f33f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#82 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#83 0x00007ffff5707ba7 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#84 0x00007ffff56f3280 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#85 0x00007ffff5ffeb73 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#86 0x00007ffff5ffe0f5 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#87 0x00007ffff5ffe4c0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#88 0x00007ffff5ffe7d2 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#89 0x00007ffff6ae92e5 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#90 0x000055555555d920 in  ()
#91 0x00007ffff62d7f6d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#92 0x00007ffff62eaac8 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#93 0x00007ffff62f33f5 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#94 0x00007ffff62f3e0f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#95 0x00007ffff65bea65 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#96 0x00007ffff65bec76 in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#97 0x000055555555dc93 in switchboard_main ()
#98 0x00007ffff59dcb97 in __libc_start_main (main=
---Type <return> to continue, or q <return> to quit---
    0x55555555ad90 <main>, argc=1, argv=0x7fffffffdef8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdee8) at ../csu/libc-start.c:310
#99 0x000055555555adca in _start ()
```
