### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Djaler** [elementary/switchboard-plug-networking#116]
I ran into a segmentation fault while trying to open networking plug. Juno

**Comment by fabianthoma** [comment]
Does not happen here, running `switchboard-plug-networking 0.1.1+r587~daily~ubuntu5.0.1`

**Comment by Djaler** [comment]
Same version. Before this I just add VPN config. Can you try this?

**Comment by Djaler** [comment]
More info from gdb:
```Thread 1 "switchboard" received signal SIGSEGV, Segmentation fault.
0x00007fffd5f47b55 in network_vpn_menu_item_construct () from /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so```

**Comment by Djaler** [comment]
```#0  0x00007fffd5f47b55 in network_vpn_menu_item_construct () from /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so
#1  0x00007fffd5f45da6 in network_vpn_page_add_connection () from /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so
#2  0x00007ffff5fd0feb in g_ptr_array_foreach () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffd5f41967 in ?? () from /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so
#4  0x00007ffff62ddcb7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff62ded45 in g_object_new_with_properties () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff62df7c1 in g_object_new () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007fffd5f32f08 in ?? () from /usr/lib/x86_64-linux-gnu/switchboard/network/libnetworking.so
#8  0x000055555555b1c1 in ?? ()
#9  0x00007ffff5ffe0f5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff5ffe4c0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff5ffe7d2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff6ae9555 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x000055555555d920 in ?? ()
#14 0x00007ffff62d7f6d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff62eaac8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff62f33f5 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff62f3e0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff65bea65 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x00007ffff65bec76 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x000055555555dc93 in switchboard_main ()
#21 0x00007ffff59dcb97 in __libc_start_main (main=0x55555555ad90 <main>, argc=1, argv=0x7fffffffdd88, init=<optimized out>, 
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd78) at ../csu/libc-start.c:310
#22 0x000055555555adca in _start ()```
